<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
/** @var \Magento\Framework\View\Element\Template $block */
?>

<?= $block->escapeHtml(__('%1 har lagts i din önskelista.', $block->getData('product_name'))) ?> <?= $block->escapeHtml(__('Klicka <a href="%1">här</a> för att fortsätta handla.', $block->getData('referer')), ['a']);
